[package]
name = "eva"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
walkdir = "2.3.2"
diesel = { version = "1.4.4", features = ["sqlite"] }
dotenv = "0.15.0"
